# Generated by Django 6.0.3 on 2026-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_user_chat_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="chat_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True, help_text="Введите ТГ ID", max_length=255, null=True, verbose_name="Тelegram ID"
            ),
        ),
    ]
