# Generated by Django 6.0.3 on 2026-03-23 15:37

import datetime

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "habit_name",
                    models.CharField(
                        help_text="Краткое название полезной привычки (например, «Утренняя зарядка»)",
                        max_length=255,
                        verbose_name="Название полезной привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Где вы будете выполнять привычку (например, «Дома», «В парке», «Офис»)",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время дня, когда вы планируете выполнять привычку (формат ЧЧ:ММ)",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Конкретное действие, которое нужно выполнить (например, «Пробежать 1 км», «Прочитать 10 страниц»)",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, если привычка приятная, а не полезная",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Периодичность выполнения в днях (1 — ежедневно, 2 — через день, 7 — еженедельно и т.д.)",
                        verbose_name="Период выполнения (в днях)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        help_text="Что вы получите за выполнение привычки (например, «Чашка кофе», «10 минут отдыха», «Эпизод сериала»)",
                        max_length=255,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_action",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        help_text="Максимальное время, которое вы потратите на выполнение (не более 120 секунд / 2 минут)",
                        validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))],
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Если отмечено, привычка будет видна другим пользователям",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, который создал эту привычку",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите привычку (не обязательно), которая будет триггером для этой (например, после «Чистка зубов» → «Медитация»)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["habit_name"],
            },
        ),
    ]
